name: Github Pages Deploy

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.17]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install npm dependencies
        working-directory: ./
        run: npm install 

      - name: Check lint errors
        working-directory: ./
        run: npm run lint
      
      - name: Run Test Cases
        working-directory: ./
        run: npm run test

      - name: Create Build
        working-directory: ./
        run: npm run build && cp docs/index.html docs/404.html

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: docs/ # The folder the action should deploy.    